### ISSUE TITLE
VACUUM TEMPORARY files limit 100 client crash 

### ISSUE THREAD

**Issue by wubx** [datafuselabs/bendsql#418]
```
databend@localhost:8000/default> VACUUM TEMPORARY files limit 100;

VACUUM TEMPORARY files
LIMIT
  100

thread 'main' panicked at cli/src/display.rs:665:73:
index out of bounds: the len is 0 but the index is 0
stack backtrace:
   0:     0x7f848d85aee2 - std::backtrace_rs::backtrace::libunwind::trace::h103e47e00552e141
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x7f848d85aee2 - std::backtrace_rs::backtrace::trace_unsynchronized::h592221613f1fd095
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f848d85aee2 - std::sys_common::backtrace::_print_fmt::hf8a30f8299b1bef3
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f848d85aee2 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5a6e3e7cc140e753
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f848d8a561c - core::fmt::rt::Argument::fmt::hd62a89729b8d4079
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/fmt/rt.rs:142:9
   5:     0x7f848d8a561c - core::fmt::write::haa8a32127a7b0d75
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/fmt/mod.rs:1153:17
   6:     0x7f848d85774f - std::io::Write::write_fmt::hc541adb06d0aeac1
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/io/mod.rs:1843:15
   7:     0x7f848d85acb4 - std::sys_common::backtrace::_print::h59dc0d5369ede572
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f848d85acb4 - std::sys_common::backtrace::print::hbb7b999054d983a7
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f848d85c2cb - std::panicking::default_hook::{{closure}}::hd143a60ad2fc5a07
  10:     0x7f848d85c023 - std::panicking::default_hook::h2aff2dd57e84e09f
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:292:9
  11:     0x7f848d85c76d - std::panicking::rust_panic_with_hook::h6811313e71f57da8
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:779:13
  12:     0x7f848d85c642 - std::panicking::begin_panic_handler::{{closure}}::h2eb4991eec554504
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:657:13
  13:     0x7f848d85b3b6 - std::sys_common::backtrace::__rust_end_short_backtrace::h05983ae26e2c8878
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x7f848d85c374 - rust_begin_unwind
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
  15:     0x7f848ce6e705 - core::panicking::panic_fmt::h49eed7d6e9368ad2
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
  16:     0x7f848ce6e8f2 - core::panicking::panic_bounds_check::hbbcac239fd960bbc
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:209:5
  17:     0x7f848cf9d4ec - bendsql::display::create_table::h4c04406b42301b45
  18:     0x7f848cf9fdce - <bendsql::display::FormatDisplay as bendsql::display::ChunkDisplay>::display::{{closure}}::h7f55b22630b30384
  19:     0x7f848cf008e4 - bendsql::session::Session::handle_query::{{closure}}::hff5a3bb51580d87e
  20:     0x7f848cea3ef6 - bendsql::main::{{closure}}::he4316773400e8214
  21:     0x7f848ce99359 - tokio::runtime::park::CachedParkThread::block_on::h7193e9e5fa192209
  22:     0x7f848cf893b7 - tokio::runtime::runtime::Runtime::block_on::h145be6491750ed84
  23:     0x7f848cfba4b7 - bendsql::main::h4573690115ff7866
  24:     0x7f848cf0ce63 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb5f56f0a86e6f60a
  25:     0x7f848cf5ee5d - std::rt::lang_start::{{closure}}::h0c7fb816e19fe8ba
  26:     0x7f848d84fc95 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h95600587cb28d946
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:284:13
  27:     0x7f848d84fc95 - std::panicking::try::do_call::h19463e8b7e5759dc
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:552:40
  28:     0x7f848d84fc95 - std::panicking::try::h9c53f8a8b4478cb2
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:516:19
  29:     0x7f848d84fc95 - std::panic::catch_unwind::h1bf2d4ddc0dfe252
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs:146:14
  30:     0x7f848d84fc95 - std::rt::lang_start_internal::{{closure}}::h974ac37711bf3c2b
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:148:48
  31:     0x7f848d84fc95 - std::panicking::try::do_call::hd0925bfa231be214
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:552:40
  32:     0x7f848d84fc95 - std::panicking::try::h4999557a22e5ef52
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:516:19
  33:     0x7f848d84fc95 - std::panic::catch_unwind::hbe1275e05de4c7ab
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs:146:14
  34:     0x7f848d84fc95 - std::rt::lang_start_internal::h14632ddfb850e80e
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:148:20
  35:     0x7f848cfba595 - main
```

**Comment by wubx** [comment]
Welcome to BendSQL 0.17.2-4a16544(2024-05-06T06:43:48.034101965Z).

**Comment by TCeason** [comment]
![image](https://github.com/datafuselabs/bendsql/assets/33082201/0e90f1df-f3db-496d-84fb-d31a6adfc8d2)

It's ok on local. Maybe you can try execute  `SELECT * FROM system.temp_files` to query the temp files.
